### ISSUE TITLE
Should this message() be a stop() instead?

### ISSUE THREAD

**Issue by adamhsparks** [gabrielblain/PowerSDI#14]
This message in OperatSDI() seems like it should be an error not just a message.

```r
if (length(parameters[, 1]) == 0) {
      message(
        "It seems that you don't have the distributions' parameters for this",
        "local and time scale(TS).\n",
        "You must first run the `ScientSDI()` function."
      )
```

your thoughts, @gabrielblain?

**Comment by gabrielblain** [comment]
Dear Adam,
You are right.
This message() should be a stop().
The user cannot run this function without the distributions' parameters
($DistPar obtained from the ScientSDI function).
Thank you.
Best
Gabriel

Em sáb., 30 de set. de 2023 às 10:12, Adam H. Sparks <
***@***.***> escreveu:

**Comment by adamhsparks** [comment]
Closed with https://github.com/gabrielblain/PowerSDI/pull/16

**Comment by adamhsparks** [comment]
closed
